package proxy

import (
	"fmt"
	"os"
	"strings"

	"DevBox/internal/project"
)

// WriteCaddyfile rewrites the front-door Caddyfile based on the current project
// list. Each project with a domain gets a vhost block that reverse-proxies to
// its resolved backend. Projects without a resolvable backend are skipped (and
// reflected in the file as a comment so users can see why their site is 404ing).
func WriteCaddyfile() error {
	projects, err := project.ListProjects()
	if err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Auto-generated by DevBox — do not edit; changes are overwritten on project changes.\n")
	sb.WriteString("{\n")
	sb.WriteString("\tadmin off\n")
	sb.WriteString("\tauto_https off\n")
	sb.WriteString("}\n\n")

	// Default landing page on :80 for the bare 127.0.0.1 hit (no Host match).
	sb.WriteString(fmt.Sprintf(":%d {\n", HTTPPort))
	sb.WriteString("\trespond \"DevBox front-door is running.\\n\\nVisit one of your registered project domains.\" 200\n")
	sb.WriteString("}\n\n")

	for _, p := range projects {
		if p.Domain == "" {
			continue
		}
		backend := ResolveBackend(p)
		if backend == "" {
			fmt.Fprintf(&sb, "# %s — skipped: no reachable backend (runtime=%q webserver=%q)\n\n",
				p.Domain, p.Runtime, p.Webserver)
			continue
		}

		fmt.Fprintf(&sb, "http://%s {\n", p.Domain)
		fmt.Fprintf(&sb, "\treverse_proxy %s {\n", backend)
		// Forward the original Host so the backend's own vhost routing picks the
		// right project (nginx server_name, FrankenPHP host matcher, etc.).
		sb.WriteString("\t\theader_up Host {host}\n")
		sb.WriteString("\t\theader_up X-Forwarded-For {remote_host}\n")
		sb.WriteString("\t\theader_up X-Forwarded-Proto {scheme}\n")
		sb.WriteString("\t}\n")
		sb.WriteString("}\n\n")
	}

	os.MkdirAll(proxyDir(), 0755)
	return os.WriteFile(caddyfilePath(), []byte(sb.String()), 0644)
}
