package proxy

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"

	"DevBox/internal/config"
	"DevBox/internal/project"
)

// WriteCaddyfile rewrites the front-door Caddyfile based on the current project
// list. Each project with a domain gets a vhost block that reverse-proxies to
// its resolved backend. Projects without a resolvable backend are skipped (and
// reflected in the file as a comment so users can see why their site is 404ing).
//
// TLS is terminated here: a project with SSL enabled and mkcert files on disk
// gets an https:// block on :443 using those files, and its http:// block
// redirects browsers to https. Traffic that already arrived over TLS upstream
// (Cloudflare tunnel → cloudflared → :80 with X-Forwarded-Proto/Cf-Visitor)
// is proxied straight through instead of being redirected into a loop.
func WriteCaddyfile() error {
	projects, err := project.ListProjects()
	if err != nil {
		return err
	}
	os.MkdirAll(proxyDir(), 0755)
	return os.WriteFile(caddyfilePath(), []byte(renderCaddyfile(projects)), 0644)
}

// renderCaddyfile builds the Caddyfile text for a project list.
func renderCaddyfile(projects []project.Project) string {
	var sb strings.Builder
	sb.WriteString("# Auto-generated by DevBox — do not edit; changes are overwritten on project changes.\n")
	sb.WriteString("{\n")
	// The admin endpoint (loopback only) is what `caddy reload` talks to; with
	// `admin off` every reload silently failed and the proxy kept serving its
	// start-up config.
	fmt.Fprintf(&sb, "\tadmin %s\n", AdminAddr)
	// We hand Caddy mkcert certificates ourselves; no ACME, no automatic
	// redirects (we write our own so tunnel traffic is not bounced).
	sb.WriteString("\tauto_https off\n")
	fmt.Fprintf(&sb, "\thttp_port %d\n", HTTPPort)
	fmt.Fprintf(&sb, "\thttps_port %d\n", HTTPSPort)
	sb.WriteString("}\n\n")

	// Default landing page on :80 for the bare 127.0.0.1 hit (no Host match).
	fmt.Fprintf(&sb, ":%d {\n", HTTPPort)
	sb.WriteString("\trespond \"DevBox front-door is running.\\n\\nVisit one of your registered project domains.\" 200\n")
	sb.WriteString("}\n\n")

	for _, p := range projects {
		if p.Domain == "" {
			continue
		}
		backend := ResolveBackend(p)
		if backend == "" {
			fmt.Fprintf(&sb, "# %s — skipped: no reachable backend (runtime=%q webserver=%q)\n\n",
				p.Domain, p.Runtime, p.Webserver)
			continue
		}

		hosts := append([]string{p.Domain}, project.ExtraHosts(p)...)
		var httpHosts []string
		for _, h := range hosts {
			httpHosts = append(httpHosts, "http://"+h)
		}

		tls := p.SSL && project.CertsExist(p.Domain)
		proxyBlock := proxyDirective(backend, tls)
		errBlock := errorPage(p)

		// ---- http:// ----
		fmt.Fprintf(&sb, "%s {\n", strings.Join(httpHosts, ", "))
		if tls {
			// Already-TLS upstream (tunnel) → proxy; plain browser hit → redirect.
			sb.WriteString("\t@xfp header X-Forwarded-Proto https\n")
			sb.WriteString("\t@cf header_regexp Cf-Visitor https\n")
			sb.WriteString("\thandle @xfp {\n" + indent(proxyBlock, 2) + "\t}\n")
			sb.WriteString("\thandle @cf {\n" + indent(proxyBlock, 2) + "\t}\n")
			sb.WriteString("\thandle {\n\t\tredir https://{host}{uri} 308\n\t}\n")
		} else {
			sb.WriteString(indent(proxyBlock, 1))
		}
		sb.WriteString(errBlock)
		sb.WriteString("}\n\n")

		// ---- https:// (mkcert only covers the local domain + wildcard) ----
		if tls {
			certFile, keyFile := project.CertPaths(p.Domain)
			fmt.Fprintf(&sb, "https://%s {\n", p.Domain)
			fmt.Fprintf(&sb, "\ttls %s %s\n", quote(certFile), quote(keyFile))
			sb.WriteString(indent(proxyBlock, 1))
			sb.WriteString(errBlock)
			sb.WriteString("}\n\n")
		}
	}

	return sb.String()
}

// proxyDirective renders the reverse_proxy block for a backend. When TLS was
// terminated at the front-door, the backend is told so via X-Forwarded-Proto
// (nginx/apache vhosts and frameworks build https:// URLs from it).
func proxyDirective(backend string, tls bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "reverse_proxy %s {\n", backend)
	// Forward the original Host so the backend's own vhost routing picks the
	// right project (nginx server_name, FrankenPHP host matcher, etc.).
	b.WriteString("\theader_up Host {host}\n")
	if tls {
		b.WriteString("\theader_up X-Forwarded-Proto https\n")
	}
	// cloudflared connects from loopback and already carries the visitor's
	// X-Forwarded-Proto (https); trusting loopback keeps it intact instead of
	// downgrading it to "http" (which would make SSL vhosts redirect-loop).
	b.WriteString("\ttrusted_proxies private_ranges\n")
	b.WriteString("}\n")
	return b.String()
}

// errorPage renders a handle_errors block that replaces Caddy's bare 502 with a
// friendly page when the backend (dev server or web server) is not running.
func errorPage(p project.Project) string {
	ws := project.ResolveWebserver(p)
	what := "web server (" + ws + ")"
	if ws == "devserver" {
		what = "dev server"
	}
	body := fmt.Sprintf(`<!doctype html><html><head><meta charset="utf-8"><title>%s — not running</title></head>
<body style="margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;background:#0f172a;color:#e2e8f0;font-family:system-ui,Segoe UI,sans-serif">
<div style="max-width:520px;padding:40px;text-align:center">
<div style="font-size:48px;margin-bottom:16px">&#9889;</div>
<h1 style="font-size:22px;margin:0 0 12px">%s is not running</h1>
<p style="color:#94a3b8;line-height:1.6;margin:0 0 24px">The %s behind <b style="color:#e2e8f0">%s</b> is stopped. Open DevBox, go to <b>Projects</b> and press <b>Start</b> — this page refreshes itself every few seconds.</p>
<p style="color:#475569;font-size:12px;margin:0">DevBox front-door &middot; backend %s</p>
</div>
<script>setTimeout(function(){location.reload()},4000)</script>
</body></html>`,
		html.EscapeString(p.Domain), html.EscapeString(p.Name), what, html.EscapeString(p.Domain), ResolveBackend(p))

	var b strings.Builder
	b.WriteString("\thandle_errors 502 503 504 {\n")
	b.WriteString("\t\theader Content-Type \"text/html; charset=utf-8\"\n")
	// Caddy strips the closing marker's indentation from every body line, so
	// each line must carry the same two tabs.
	b.WriteString("\t\trespond <<HTML\n")
	b.WriteString(indent(body, 2))
	b.WriteString("\t\tHTML 503\n")
	b.WriteString("\t}\n")
	return b.String()
}

func indent(s string, tabs int) string {
	pad := strings.Repeat("\t", tabs)
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, l := range lines {
		lines[i] = pad + l
	}
	return strings.Join(lines, "\n") + "\n"
}

func quote(path string) string {
	return "\"" + strings.ReplaceAll(filepath.ToSlash(path), "\"", "\\\"") + "\""
}

// TLSAtFrontDoor reports whether HTTPS for project domains is expected to be
// terminated by the front-door (installed + enabled). Vhost generators use it
// to leave :443 alone so both can't fight over the port.
func TLSAtFrontDoor() bool {
	cfg := config.Get()
	return cfg != nil && cfg.ProxyEnabled && IsInstalled()
}
