// Package terminal opens the user's own terminal emulator with a DevBox
// environment: a working directory, a PATH that starts with the right
// runtime/tool folders, extra variables and an optional command to run first
// (e.g. `psql` already connected to the DevBox PostgreSQL).
//
// DevBox deliberately does not embed a terminal — Windows Terminal, iTerm and
// friends are better at being terminals. What DevBox adds is the environment,
// carried through a small generated init script so it survives terminals that
// hand the shell off to an already-running host process (Windows Terminal).
package terminal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"DevBox/internal/config"
)

// Terminal is one launcher DevBox knows how to drive.
type Terminal struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Shell     string `json:"shell"`     // pwsh | powershell | cmd | bash | zsh
	Path      string `json:"path"`      // executable / app location
	Installed bool   `json:"installed"` // detected on this machine
}

// Session describes what to open.
type Session struct {
	Title string            // shown in the prompt / window title, e.g. "myapp" or "postgres"
	Dir   string            // working directory ("" = home)
	Path  []string          // directories to prepend to PATH, in order
	Env   map[string]string // extra environment variables
	Cmd   string            // optional command to run before handing over the prompt
}

// List returns the terminals available on this machine, best first. The
// user's preferred one (config.Terminal) is moved to the front when installed.
func List() []Terminal {
	all := detect()
	pref := config.Get().Terminal
	if pref == "" {
		return all
	}
	for i, t := range all {
		if t.ID == pref && t.Installed {
			return append([]Terminal{t}, append(append([]Terminal{}, all[:i]...), all[i+1:]...)...)
		}
	}
	return all
}

// Open launches the preferred (or first installed) terminal for a session.
func Open(s Session) error {
	var chosen *Terminal
	for _, t := range List() {
		if t.Installed {
			tt := t
			chosen = &tt
			break
		}
	}
	if chosen == nil {
		return fmt.Errorf("no terminal found")
	}
	return OpenWith(chosen.ID, s)
}

// OpenWith launches a specific terminal for a session.
func OpenWith(id string, s Session) error {
	var chosen *Terminal
	for _, t := range detect() {
		if t.ID == id {
			tt := t
			chosen = &tt
			break
		}
	}
	if chosen == nil || !chosen.Installed {
		return fmt.Errorf("terminal %q is not available", id)
	}
	if s.Dir == "" {
		s.Dir, _ = os.UserHomeDir()
	}
	script, err := writeInitScript(chosen.Shell, s)
	if err != nil {
		return err
	}
	return launch(*chosen, s, script)
}

// scriptsDir holds the generated init scripts; old ones are pruned on each call.
func scriptsDir() string {
	dir := filepath.Join(config.GetDataDir(), "tmp", "terminal")
	os.MkdirAll(dir, 0755)
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if info, err := e.Info(); err == nil && time.Since(info.ModTime()) > 24*time.Hour {
			os.Remove(filepath.Join(dir, e.Name()))
		}
	}
	return dir
}

// writeInitScript renders the per-shell startup file for a session.
func writeInitScript(shell string, s Session) (string, error) {
	tag := s.Title
	if tag == "" {
		tag = "devbox"
	}
	name := fmt.Sprintf("devbox-%s-%d", sanitize(tag), time.Now().UnixNano()%1_000_000)
	var body, ext string
	switch shell {
	case "pwsh", "powershell":
		ext = ".ps1"
		body = renderPowerShell(tag, s)
	case "cmd":
		ext = ".cmd"
		body = renderCmd(tag, s)
	default: // bash / zsh
		ext = ".sh"
		body = renderPosix(tag, s)
	}
	p := filepath.Join(scriptsDir(), name+ext)
	return p, os.WriteFile(p, []byte(body), 0644)
}

func sanitize(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			b.WriteRune(r)
		} else {
			b.WriteByte('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

func psQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }
func shQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

func renderPowerShell(tag string, s Session) string {
	var b strings.Builder
	b.WriteString("# Generated by DevBox — terminal environment\n")
	if len(s.Path) > 0 {
		fmt.Fprintf(&b, "$env:PATH = %s + [IO.Path]::PathSeparator + $env:PATH\n", psQuote(strings.Join(s.Path, string(os.PathListSeparator))))
	}
	for k, v := range s.Env {
		fmt.Fprintf(&b, "$env:%s = %s\n", k, psQuote(v))
	}
	fmt.Fprintf(&b, "$env:DEVBOX_SESSION = %s\n", psQuote(tag))
	fmt.Fprintf(&b, "Set-Location -LiteralPath %s\n", psQuote(s.Dir))
	fmt.Fprintf(&b, "$Host.UI.RawUI.WindowTitle = %s\n", psQuote("DevBox · "+tag))
	fmt.Fprintf(&b, "function global:prompt { \"`e[36mdevbox`e[0m:`e[1m%s`e[0m \" + (Get-Location).Path + \"> \" }\n", strings.ReplaceAll(tag, "\"", ""))
	fmt.Fprintf(&b, "Write-Host \"DevBox terminal — %s\" -ForegroundColor Cyan\n", strings.ReplaceAll(tag, "\"", ""))
	if len(s.Path) > 0 {
		b.WriteString("Write-Host ('PATH+ ' + " + psQuote(strings.Join(s.Path, "; ")) + ") -ForegroundColor DarkGray\n")
	}
	if s.Cmd != "" {
		fmt.Fprintf(&b, "Write-Host %s -ForegroundColor DarkGray\n", psQuote("> "+s.Cmd))
		fmt.Fprintf(&b, "%s\n", s.Cmd)
	}
	return b.String()
}

func renderCmd(tag string, s Session) string {
	var b strings.Builder
	b.WriteString("@echo off\r\nrem Generated by DevBox - terminal environment\r\n")
	if len(s.Path) > 0 {
		fmt.Fprintf(&b, "set \"PATH=%s;%%PATH%%\"\r\n", strings.Join(s.Path, ";"))
	}
	for k, v := range s.Env {
		fmt.Fprintf(&b, "set \"%s=%s\"\r\n", k, v)
	}
	fmt.Fprintf(&b, "set \"DEVBOX_SESSION=%s\"\r\n", tag)
	fmt.Fprintf(&b, "cd /d \"%s\"\r\n", s.Dir)
	fmt.Fprintf(&b, "title DevBox - %s\r\n", tag)
	fmt.Fprintf(&b, "prompt devbox:%s $P$G\r\n", tag)
	fmt.Fprintf(&b, "echo DevBox terminal - %s\r\n", tag)
	if s.Cmd != "" {
		fmt.Fprintf(&b, "echo ^> %s\r\n%s\r\n", s.Cmd, s.Cmd)
	}
	return b.String()
}

func renderPosix(tag string, s Session) string {
	var b strings.Builder
	b.WriteString("# Generated by DevBox — terminal environment\n")
	// Keep the user's own rc so aliases/prompts survive.
	b.WriteString("[ -f ~/.bashrc ] && . ~/.bashrc\n[ -n \"$ZSH_VERSION\" ] && [ -f ~/.zshrc ] && . ~/.zshrc\n")
	if len(s.Path) > 0 {
		paths := make([]string, len(s.Path))
		for i, p := range s.Path {
			paths[i] = toPosixPath(p)
		}
		fmt.Fprintf(&b, "export PATH=%s:\"$PATH\"\n", shQuote(strings.Join(paths, ":")))
	}
	for k, v := range s.Env {
		fmt.Fprintf(&b, "export %s=%s\n", k, shQuote(v))
	}
	fmt.Fprintf(&b, "export DEVBOX_SESSION=%s\n", shQuote(tag))
	fmt.Fprintf(&b, "cd %s\n", shQuote(toPosixPath(s.Dir)))
	fmt.Fprintf(&b, "export PS1='\\[\\e[36m\\]devbox\\[\\e[0m\\]:\\[\\e[1m\\]%s\\[\\e[0m\\] \\w\\$ '\n", strings.ReplaceAll(tag, "'", ""))
	fmt.Fprintf(&b, "printf '\\033[36mDevBox terminal — %s\\033[0m\\n'\n", strings.ReplaceAll(tag, "'", ""))
	if s.Cmd != "" {
		fmt.Fprintf(&b, "printf '\\033[90m> %%s\\033[0m\\n' %s\n%s\n", shQuote(s.Cmd), s.Cmd)
	}
	return b.String()
}

// toPosixPath converts C:\x\y to /c/x/y for Git Bash / MSYS; other paths are
// returned unchanged.
func toPosixPath(p string) string {
	if len(p) >= 2 && p[1] == ':' {
		drive := strings.ToLower(p[:1])
		rest := strings.ReplaceAll(p[2:], "\\", "/")
		return "/" + drive + rest
	}
	return p
}
