// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['main']['App']['AddProject'](arg1, arg2);
}

export function AddToPATH(arg1) {
  return window['go']['main']['App']['AddToPATH'](arg1);
}

export function CheckPort(arg1) {
  return window['go']['main']['App']['CheckPort'](arg1);
}

export function CloneGitProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloneGitProject'](arg1, arg2, arg3, arg4);
}

export function DetectExternalDBTools() {
  return window['go']['main']['App']['DetectExternalDBTools']();
}

export function DetectFramework(arg1) {
  return window['go']['main']['App']['DetectFramework'](arg1);
}

export function GetAllServices() {
  return window['go']['main']['App']['GetAllServices']();
}

export function GetAutoStartServices() {
  return window['go']['main']['App']['GetAutoStartServices']();
}

export function GetAvailableLanguages() {
  return window['go']['main']['App']['GetAvailableLanguages']();
}

export function GetAvailableTemplates() {
  return window['go']['main']['App']['GetAvailableTemplates']();
}

export function GetBunVersion() {
  return window['go']['main']['App']['GetBunVersion']();
}

export function GetComposerVersion() {
  return window['go']['main']['App']['GetComposerVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDevServerLogs(arg1, arg2) {
  return window['go']['main']['App']['GetDevServerLogs'](arg1, arg2);
}

export function GetGlobalRuntime(arg1) {
  return window['go']['main']['App']['GetGlobalRuntime'](arg1);
}

export function GetInstalledRuntimes() {
  return window['go']['main']['App']['GetInstalledRuntimes']();
}

export function GetInstalledVersions(arg1) {
  return window['go']['main']['App']['GetInstalledVersions'](arg1);
}

export function GetLocale(arg1) {
  return window['go']['main']['App']['GetLocale'](arg1);
}

export function GetPATHEntries() {
  return window['go']['main']['App']['GetPATHEntries']();
}

export function GetPHPExtensions(arg1) {
  return window['go']['main']['App']['GetPHPExtensions'](arg1);
}

export function GetProjectVhostPath(arg1) {
  return window['go']['main']['App']['GetProjectVhostPath'](arg1);
}

export function GetRemoteVersions(arg1) {
  return window['go']['main']['App']['GetRemoteVersions'](arg1);
}

export function GetRunningDevServers() {
  return window['go']['main']['App']['GetRunningDevServers']();
}

export function GetRunningTunnels() {
  return window['go']['main']['App']['GetRunningTunnels']();
}

export function GetServiceDetails(arg1) {
  return window['go']['main']['App']['GetServiceDetails'](arg1);
}

export function GetServiceLogs(arg1, arg2) {
  return window['go']['main']['App']['GetServiceLogs'](arg1, arg2);
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function GetServiceVersions(arg1) {
  return window['go']['main']['App']['GetServiceVersions'](arg1);
}

export function GetTunnelURL(arg1) {
  return window['go']['main']['App']['GetTunnelURL'](arg1);
}

export function GetWebServerPort() {
  return window['go']['main']['App']['GetWebServerPort']();
}

export function InstallAdminer() {
  return window['go']['main']['App']['InstallAdminer']();
}

export function InstallBun() {
  return window['go']['main']['App']['InstallBun']();
}

export function InstallCloudflared() {
  return window['go']['main']['App']['InstallCloudflared']();
}

export function InstallComposer() {
  return window['go']['main']['App']['InstallComposer']();
}

export function InstallRuntime(arg1, arg2) {
  return window['go']['main']['App']['InstallRuntime'](arg1, arg2);
}

export function InstallService(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallService'](arg1, arg2, arg3);
}

export function IsAdminerInstalled() {
  return window['go']['main']['App']['IsAdminerInstalled']();
}

export function IsBunInstalled() {
  return window['go']['main']['App']['IsBunInstalled']();
}

export function IsCloudflaredInstalled() {
  return window['go']['main']['App']['IsCloudflaredInstalled']();
}

export function IsComposerInstalled() {
  return window['go']['main']['App']['IsComposerInstalled']();
}

export function IsDevServerRunning(arg1) {
  return window['go']['main']['App']['IsDevServerRunning'](arg1);
}

export function IsGitInstalled() {
  return window['go']['main']['App']['IsGitInstalled']();
}

export function IsPHPCGIRunning() {
  return window['go']['main']['App']['IsPHPCGIRunning']();
}

export function IsTunnelRunning(arg1) {
  return window['go']['main']['App']['IsTunnelRunning'](arg1);
}

export function LaunchExternalTool(arg1, arg2) {
  return window['go']['main']['App']['LaunchExternalTool'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenFileInEditor(arg1) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenProjectFolder(arg1) {
  return window['go']['main']['App']['OpenProjectFolder'](arg1);
}

export function RemoveFromPATH(arg1) {
  return window['go']['main']['App']['RemoveFromPATH'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function ScaffoldNewProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScaffoldNewProject'](arg1, arg2, arg3, arg4);
}

export function SelectParentFolder() {
  return window['go']['main']['App']['SelectParentFolder']();
}

export function SelectProjectFolder() {
  return window['go']['main']['App']['SelectProjectFolder']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetGlobalRuntime(arg1, arg2) {
  return window['go']['main']['App']['SetGlobalRuntime'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetProjectPort(arg1, arg2) {
  return window['go']['main']['App']['SetProjectPort'](arg1, arg2);
}

export function SetProjectStartCommand(arg1, arg2) {
  return window['go']['main']['App']['SetProjectStartCommand'](arg1, arg2);
}

export function SetServiceAutoStart(arg1, arg2) {
  return window['go']['main']['App']['SetServiceAutoStart'](arg1, arg2);
}

export function SetServicePort(arg1, arg2) {
  return window['go']['main']['App']['SetServicePort'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetupProjectDomain(arg1) {
  return window['go']['main']['App']['SetupProjectDomain'](arg1);
}

export function SetupProjectSSL(arg1) {
  return window['go']['main']['App']['SetupProjectSSL'](arg1);
}

export function StartDevServer(arg1) {
  return window['go']['main']['App']['StartDevServer'](arg1);
}

export function StartPHPCGI(arg1, arg2) {
  return window['go']['main']['App']['StartPHPCGI'](arg1, arg2);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StartTunnel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3, arg4);
}

export function StopDevServer(arg1) {
  return window['go']['main']['App']['StopDevServer'](arg1);
}

export function StopPHPCGI() {
  return window['go']['main']['App']['StopPHPCGI']();
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function TogglePHPExtension(arg1, arg2, arg3) {
  return window['go']['main']['App']['TogglePHPExtension'](arg1, arg2, arg3);
}

export function ToggleProjectSSL(arg1, arg2) {
  return window['go']['main']['App']['ToggleProjectSSL'](arg1, arg2);
}

export function UninstallBun() {
  return window['go']['main']['App']['UninstallBun']();
}

export function UninstallRuntime(arg1, arg2) {
  return window['go']['main']['App']['UninstallRuntime'](arg1, arg2);
}

export function UninstallService(arg1) {
  return window['go']['main']['App']['UninstallService'](arg1);
}
