// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {service} from '../models';
import {tools} from '../models';
import {config} from '../models';
import {main} from '../models';
import {runtime} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<project.Project>;

export function AddToPATH(arg1:string):Promise<void>;

export function CheckPort(arg1:number):Promise<service.PortStatus>;

export function CloneGitProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DetectExternalDBTools():Promise<Array<tools.ExternalTool>>;

export function DetectFramework(arg1:string):Promise<string>;

export function GetAllServices():Promise<Record<string, service.ServiceInfo>>;

export function GetAutoStartServices():Promise<Array<string>>;

export function GetAvailableLanguages():Promise<Array<string>>;

export function GetAvailableTemplates():Promise<Array<project.FrameworkTemplate>>;

export function GetBunVersion():Promise<string>;

export function GetComposerVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetDevServerLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetGlobalRuntime(arg1:string):Promise<string>;

export function GetInstalledRuntimes():Promise<Record<string, Array<string>>>;

export function GetInstalledVersions(arg1:string):Promise<Array<main.RuntimeVersionInfo>>;

export function GetLocale(arg1:string):Promise<Record<string, string>>;

export function GetPATHEntries():Promise<Array<string>>;

export function GetPHPExtensions(arg1:string):Promise<Array<runtime.PHPExtension>>;

export function GetProjectVhostPath(arg1:string):Promise<string>;

export function GetRemoteVersions(arg1:string):Promise<Array<main.RuntimeVersionInfo>>;

export function GetRunningDevServers():Promise<Record<string, number>>;

export function GetRunningTunnels():Promise<Record<string, string>>;

export function GetServiceDetails(arg1:string):Promise<main.ServiceDetailInfo>;

export function GetServiceLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetServiceStatus():Promise<Record<string, string>>;

export function GetServiceVersions(arg1:string):Promise<Array<service.AvailableVersion>>;

export function GetTunnelURL(arg1:string):Promise<string>;

export function GetWebServerPort():Promise<number>;

export function InstallAdminer():Promise<void>;

export function InstallBun():Promise<void>;

export function InstallCloudflared():Promise<void>;

export function InstallComposer():Promise<void>;

export function InstallRuntime(arg1:string,arg2:string):Promise<void>;

export function InstallService(arg1:string,arg2:string,arg3:number):Promise<void>;

export function IsAdminerInstalled():Promise<boolean>;

export function IsBunInstalled():Promise<boolean>;

export function IsCloudflaredInstalled():Promise<boolean>;

export function IsComposerInstalled():Promise<boolean>;

export function IsDevServerRunning(arg1:string):Promise<boolean>;

export function IsGitInstalled():Promise<boolean>;

export function IsPHPCGIRunning():Promise<boolean>;

export function IsTunnelRunning(arg1:string):Promise<boolean>;

export function LaunchExternalTool(arg1:string,arg2:string):Promise<void>;

export function ListProjects():Promise<Array<project.Project>>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenProjectFolder(arg1:string):Promise<void>;

export function RemoveFromPATH(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function ScaffoldNewProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SelectParentFolder():Promise<string>;

export function SelectProjectFolder():Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetGlobalRuntime(arg1:string,arg2:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetProjectPort(arg1:string,arg2:number):Promise<void>;

export function SetProjectStartCommand(arg1:string,arg2:string):Promise<void>;

export function SetServiceAutoStart(arg1:string,arg2:boolean):Promise<void>;

export function SetServicePort(arg1:string,arg2:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetupProjectDomain(arg1:string):Promise<void>;

export function SetupProjectSSL(arg1:string):Promise<void>;

export function StartDevServer(arg1:string):Promise<void>;

export function StartPHPCGI(arg1:string,arg2:number):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StartTunnel(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function StopDevServer(arg1:string):Promise<void>;

export function StopPHPCGI():Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function TogglePHPExtension(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ToggleProjectSSL(arg1:string,arg2:boolean):Promise<void>;

export function UninstallBun():Promise<void>;

export function UninstallRuntime(arg1:string,arg2:string):Promise<void>;

export function UninstallService(arg1:string):Promise<void>;
