// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {updater} from '../models';
import {service} from '../models';
import {tools} from '../models';
import {tunnel} from '../models';
import {config} from '../models';
import {devtools} from '../models';
import {main} from '../models';
import {runtime} from '../models';
import {terminal} from '../models';
import {discovery} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<project.Project>;

export function AddToPATH(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<updater.Release>;

export function CheckPort(arg1:number):Promise<service.PortStatus>;

export function CloneGitProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ConfigureCloudflare(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DetectExternalDBTools():Promise<Array<tools.ExternalTool>>;

export function DetectFramework(arg1:string):Promise<string>;

export function DisablePnpm():Promise<void>;

export function DisableYarn():Promise<void>;

export function DisconnectCloudflare():Promise<void>;

export function EnablePnpm():Promise<void>;

export function EnableYarn():Promise<void>;

export function FixProjectEnvHints(arg1:string):Promise<number>;

export function GetAdminerURL():Promise<string>;

export function GetAllServices():Promise<Record<string, service.ServiceInfo>>;

export function GetAppVersion():Promise<string>;

export function GetAutoStartServices():Promise<Array<string>>;

export function GetAvailableLanguages():Promise<Array<string>>;

export function GetAvailableTemplates():Promise<Array<project.FrameworkTemplate>>;

export function GetBunVersion():Promise<string>;

export function GetCloudflareStatus():Promise<tunnel.CloudflareStatus>;

export function GetComposerVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetDataDir():Promise<string>;

export function GetDefaultProjectsDir():Promise<string>;

export function GetDevServerLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetDevTools():Promise<Array<devtools.Status>>;

export function GetFrameworkCatalog():Promise<Array<project.Framework>>;

export function GetGlobalRuntime(arg1:string):Promise<string>;

export function GetInstalledCounts():Promise<Record<string, number>>;

export function GetInstalledRuntimes():Promise<Record<string, Array<string>>>;

export function GetInstalledVersions(arg1:string):Promise<Array<main.RuntimeVersionInfo>>;

export function GetLastUpdateCheck():Promise<updater.Release>;

export function GetLocale(arg1:string):Promise<Record<string, string>>;

export function GetMigrationNotice():Promise<main.MigrationNotice>;

export function GetNpmLatestVersion():Promise<string>;

export function GetNpmVersion():Promise<string>;

export function GetPATHEntries():Promise<Array<string>>;

export function GetPHPCGIInstances():Promise<Array<runtime.PHPCGIInstance>>;

export function GetPHPExtensions(arg1:string):Promise<Array<runtime.PHPExtension>>;

export function GetPHPIniPath(arg1:string):Promise<string>;

export function GetPHPIniSettings(arg1:string):Promise<Record<string, string>>;

export function GetPeclExtensions(arg1:string):Promise<Array<runtime.PeclExtension>>;

export function GetPnpmVersion():Promise<string>;

export function GetProjectEnvHints(arg1:string):Promise<Array<project.EnvHint>>;

export function GetProjectVhostPath(arg1:string):Promise<string>;

export function GetProxyLogPath():Promise<string>;

export function GetProxyStatus():Promise<main.ProxyStatus>;

export function GetRemoteVersions(arg1:string):Promise<Array<main.RuntimeVersionInfo>>;

export function GetRemoteVersionsInfo(arg1:string,arg2:boolean):Promise<main.RemoteVersionsResult>;

export function GetRunningDevServers():Promise<Record<string, number>>;

export function GetRunningTunnels():Promise<Record<string, string>>;

export function GetRuntimeUpdates(arg1:string):Promise<Array<runtime.RuntimeUpdate>>;

export function GetServiceDetails(arg1:string):Promise<main.ServiceDetailInfo>;

export function GetServiceLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetServiceStatus():Promise<Record<string, string>>;

export function GetServiceVersions(arg1:string):Promise<Array<service.AvailableVersion>>;

export function GetTunnelURL(arg1:string):Promise<string>;

export function GetWebServerPort():Promise<number>;

export function GetYarnVersion():Promise<string>;

export function HideToTray():Promise<void>;

export function ImportExternalRuntime(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportExternalService(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InstallAdminer():Promise<void>;

export function InstallAppUpdate():Promise<void>;

export function InstallBun():Promise<void>;

export function InstallCloudflared():Promise<void>;

export function InstallComposer():Promise<void>;

export function InstallDevTool(arg1:string):Promise<void>;

export function InstallPeclExtension(arg1:string,arg2:string):Promise<void>;

export function InstallProxy():Promise<void>;

export function InstallRuntime(arg1:string,arg2:string):Promise<void>;

export function InstallService(arg1:string,arg2:string,arg3:number):Promise<void>;

export function IsAdminerInstalled():Promise<boolean>;

export function IsAdminerServerRunning():Promise<boolean>;

export function IsAutoStartEnabled():Promise<boolean>;

export function IsBunInstalled():Promise<boolean>;

export function IsCloudflaredInstalled():Promise<boolean>;

export function IsComposerInstalled():Promise<boolean>;

export function IsDevServerRunning(arg1:string):Promise<boolean>;

export function IsGitInstalled():Promise<boolean>;

export function IsPHPCGIRunning():Promise<boolean>;

export function IsPnpmEnabled():Promise<boolean>;

export function IsTunnelRunning(arg1:string):Promise<boolean>;

export function IsYarnEnabled():Promise<boolean>;

export function LaunchExternalTool(arg1:string,arg2:string):Promise<void>;

export function ListProjects():Promise<Array<project.Project>>;

export function ListTerminals():Promise<Array<terminal.Terminal>>;

export function OpenAdminer():Promise<void>;

export function OpenDataDir():Promise<void>;

export function OpenDevTool(arg1:string):Promise<void>;

export function OpenFileInEditor(arg1:string):Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenProjectFolder(arg1:string):Promise<void>;

export function OpenProjectTerminal(arg1:string):Promise<void>;

export function OpenServiceTerminal(arg1:string):Promise<void>;

export function OpenTerminal():Promise<void>;

export function Quit():Promise<void>;

export function RefreshAllVersions():Promise<void>;

export function RefreshServiceVersions(arg1:string):Promise<Array<service.AvailableVersion>>;

export function RegenerateVhosts():Promise<void>;

export function ReloadProxy():Promise<void>;

export function RemoveFromPATH(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RestartPHPCGI():Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function ScaffoldNewProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ScanExternalSoftware(arg1:boolean):Promise<Array<discovery.Found>>;

export function SelectParentFolder():Promise<string>;

export function SelectProjectFolder():Promise<string>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SetGlobalRuntime(arg1:string,arg2:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetPHPIniSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetProjectAutoStart(arg1:string,arg2:boolean):Promise<void>;

export function SetProjectPort(arg1:string,arg2:number):Promise<void>;

export function SetProjectPublicHostname(arg1:string,arg2:string):Promise<void>;

export function SetProjectRuntime(arg1:string,arg2:string):Promise<void>;

export function SetProjectRuntimeVersion(arg1:string,arg2:string):Promise<void>;

export function SetProjectStartCommand(arg1:string,arg2:string):Promise<void>;

export function SetProjectWebserver(arg1:string,arg2:string):Promise<void>;

export function SetServiceAutoStart(arg1:string,arg2:boolean):Promise<void>;

export function SetServicePort(arg1:string,arg2:number):Promise<void>;

export function SetServiceSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetStartMinimized(arg1:boolean):Promise<void>;

export function SetTerminal(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetupProjectDomain(arg1:string):Promise<void>;

export function SetupProjectSSL(arg1:string):Promise<void>;

export function StartDevServer(arg1:string):Promise<void>;

export function StartPHPCGI(arg1:string,arg2:number):Promise<void>;

export function StartProxy():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StartTunnel(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function StopAdminerServer():Promise<void>;

export function StopDevServer(arg1:string):Promise<void>;

export function StopDevTool(arg1:string):Promise<void>;

export function StopPHPCGI():Promise<void>;

export function StopProxy():Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function TogglePHPExtension(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ToggleProjectSSL(arg1:string,arg2:boolean):Promise<void>;

export function UninstallAdminer():Promise<void>;

export function UninstallBun():Promise<void>;

export function UninstallDevTool(arg1:string):Promise<void>;

export function UninstallPeclExtension(arg1:string,arg2:string):Promise<void>;

export function UninstallProxy():Promise<void>;

export function UninstallRuntime(arg1:string,arg2:string):Promise<void>;

export function UninstallService(arg1:string):Promise<void>;

export function UpdateNpm():Promise<void>;

export function UpdateRuntime(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateService(arg1:string,arg2:string):Promise<void>;

export function VerifyCloudflareToken(arg1:string):Promise<main.CloudflareVerifyResult>;
